Application/WebApplicationBlog/Controllers/RegNuevoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplicationBlog.Models;
using System.Net.Http;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json.Serialization;
using System.IO;
namespace WebApplicationBlog.Controllers
{
    public class RegNuevoController : Controller
    {
        // GET: RegNuevoController
     
        public ActionResult Index()
        {
             return View();
        }
     
        //GET: RegNuevoController/Create
        [HttpPost]
        public ActionResult Index(Noticia art)
        {
            //Articles articles = new Articles();
           

            if (ModelState.IsValid)
            {
                createNewReg(art);
               // RedirectToAction("Index", "Blog");
            }

            return View();
        }


        public async Task<IActionResult> createNewReg(Noticia article)
        {

           

            string apiUrl = Environment.GetEnvironmentVariable("urllocal");
            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(article), System.Text.Encoding.UTF8, "application/json");
                using (var response = await httpClient.PostAsync(apiUrl, content))
                {
                   
                    var apiResponse = response;
                   // await Response.WriteAsync("<script>window.alert('Registro guardado!')</script>");
                    


                }

            }
           // RedirectToPage("../");

            return View();

        }
    }


         
    
}

Application/WebApplicationBlog/Views/RegNuevo/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@{
    // @Model Articles;
    // Articles articulo;//= new Articles();//= (Articles)ViewBag.articulo;
    // ViewBag.articulo = articulo;
}

<h2>Crear Articulos</h2>

@model Noticia
@using (Html.BeginForm("Index", "RegNuevo", FormMethod.Post))
{
    <div>
        <div class="col-md-12">
            <div class="col-md-1">
                @Html.LabelFor(d => d.Titulo)

            </div>
            <div class="col-md-1">
                @Html.TextBoxFor(d => d.Titulo, "titulo", new { @class = "fore-control", required = "required" })

            </div>
        </div>
        <div class="col-md-12">
            <div class="col-md-1">
                @Html.LabelFor(d => d.Descripcion)
            </div>
            <div class="col-md-1">
                @Html.TextBoxFor(d => d.Descripcion, "description", new { @class = "fore-control", required = "required" })
            </div>
        </div>
        <div class="col-md-12">
            <div class="col-md-1">
                @Html.LabelFor(d => d.Contenido)
            </div>
            <div class="col-md-1">
                @Html.TextBoxFor(d => d.Contenido, "contenido", new { @class = "fore-control", required = "required" })
            </div>
        </div>

        <div class="col-md-12">
            <div class="col-md-1">
                @Html.LabelFor(d => d.url)
            </div>
            <div class="col-md-1">
                @Html.TextBoxFor(d => d.url, "Url", new { @class = "fore-control", required = "required" })
            </div>
        </div>
        <div class="col-md-12">
            <div class="col-md-1">
                @Html.LabelFor(d => d.imagen)
            </div>
            <div class="col-md-1">
                <input type="file" name="Imagen" />
                <span asp-validation-for="imagen"></span>

            </div>
        </div>
        <br />

    </div>
    <div class="col-md-1">  <input type="submit" value="Guardar" /></div>
}